#+TITLE:       A script for indecisive doms and daredevil butt-gamblers
#+AUTHOR:      thingywhat
#+EMAIL:       thingywhat@Dee
#+DATE:        2015-01-22 Thu
#+URI:         /blog/%y/%m/%d/A script for indecisive doms and daredevil butt-gamblers
#+KEYWORDS:    spanking,lisp,script,javascript
#+TAGS:        spanking,lisp,script,javascript
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: A spanking randomizer

Maybe you like to gamble? Maybe you need to make a decision without
/you/ actually deciding? Maybe you have a top who is indecisive? Who
knows?

Either way, you are *definitely* getting a spanking...

But you or your top have decided to leave /how/ it will happen to
chance. Duration, position, implement, etc...

What kind of spanking will you get? Nobody knows, except you, because
it is displayed below this line:

#+BEGIN_HTML
<pre id="output" style="white-space: pre-wrap; word-wrap: break-word;"></pre>
<script type="text/javascript">
window.onload = function(){
  gamble();
};

var gamble = (function(){
  var maximum = 100;
  var minimum = 10;

  var implement = [
    {name:"hand", verb: "handspanked", adjectives:["heavy"]},
    {name:"belt", verb:"belted", adjectives:["leather"]},
    {name:"cane", verb:"caned", adjectives:["wicked","ratten","fierce"]},
    {name:"switch", verb:"switched", adjectives:["tiny","swift"]},
    {name:"brush", verb:"spanked", adjectives:["heavy","bath","hair","wooden"]},
    {name:"paddle", verb:"paddled", adjectives:["lexan","wooden","hole-filled","frat","ping-pong"]},
    {name:"spoon", verb:"spanked", adjectives:["wooden","mixing","slotted"]}
  ];
  
  var position = ["over-the-knee", "diaper", "bent-over", "under-arm", "prone"];
  
  var dress = ["over your pants", "on your underwear", "pantsless", "naked"];
  
  function random(min, max){
    return min + Math.floor(Math.random() * (max - min));
  }
  function pick(array){
    return array[random(0, array.length)];
  }

  return function(){
    var impl = pick(implement);
    var pos = pick(position);
    var state = pick(dress);
    
      document.getElementById("output").innerHTML = "You should be " +
      impl.verb + " " + state + " " + random(minimum, maximum) +
      " times in the " + pos + " position with a " +
      pick(impl.adjectives) + " " + impl.name;
  };
})();
</script>
#+END_HTML
